### Send POST request with json body
POST http://localhost:8080/value/
Content-Type: application/json

{
  "id": "FreeMemory",
  "type": "gauge"
}

### Send POST request with json body
POST http://localhost:8080/update/unknown/testCounter/100
Content-Type: text/plain

### Send POST request with json body
POST http://localhost:8080/update
Content-Type: application/json

{
  "id": "PollCount",
  "type": "counter",
  "delta": 6634086670,
  "hash": ""
}

### GET request with a header
GET http://localhost:8080/
Accept: html/text

### Send POST request with json body
POST http://localhost:8080/update/counter/testCounter/100
Content-Type: text/plain